// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import frc.robot.subsystems.Ludwig.LudwigDriveTrain;
public class DriveSubsystem extends LudwigDriveTrain{}

//import frc.robot.subsystems.Eddie.EddieDriveTrain;
//public class DriveSubsystem extends EddieDriveTrain{}
